---
- name: Create group
  group:
    name: gamoto
    state: present
    system: true

- name: Create uid
  user:
    name: gamoto
    group: gamoto
    system: true
    home: /var/lib/gamoto
    shell: /bin/false

- file:
    path: /var/lib/gamoto
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto/users
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto/ca
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

# XXX This needs to be a lot more precise
- name: Sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^gamoto'
    line: 'gamoto   ALL=(ALL) NOPASSWD: ALL'
# XXX

  
