---
- name: Create gamoto group
  group:
    name: gamoto
    state: present
    system: true

- name: Create gamoto uid
  user:
    name: gamoto
    group: gamoto
    system: true
    home: /var/lib/gamoto
    shell: /bin/false

- name: Configure paths
  file:
    path: /etc/gamoto
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto/users
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto/ca
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- file:
    path: /var/lib/gamoto/ccd
    state: directory
    owner: gamoto
    group: gamoto
    mode: 0755

- name: Install packages
  package:
    name:
      - python3-pip
      - python3-setuptools
      - python-setuptools
    state: latest

- name: Install Gamoto
  pip:
    name: gamoto
    executable: /usr/bin/pip3

- name: Configure Gamoto 
  template:
    src: gamoto.conf
    dest: /etc/gamoto/gamoto.conf

- name: Configure systemd
  copy:
    src: gamoto.service
    dest: /lib/systemd/system/gamoto.service

- name: Create database
  shell: gamoto migrate
  args:
    creates: /var/lib/gamoto/gamoto.db

- name: Build static cache
  shell: gamoto collectstatic --noinput
  args:
    creates: /var/lib/gamoto/static/main.css

- name: Configure sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^gamoto'
    line: 'gamoto   ALL=(ALL) NOPASSWD: /bin/cat,/bin/chmod,/bin/chown,/bin/mkdir,/usr/sbin/useradd,/usr/bin/stat,/usr/bin/tee'

- name: Generate CA (this takes a while first time)
  shell: gamoto setup
  args:
    creates: /var/lib/gamoto/ca/ca.crt

- name: Start Gamoto
  systemd:
    name: gamoto
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Start OpenVPN service
  systemd:
    name: 'openvpn@gamoto'
    state: restarted

- name: Restart nginx (You may want to add your own SSL)
  systemd:
    name: 'nginx'
    state: restarted
    enabled: yes
