---
- name: Install packages
  package:
    name:
      - openvpn
      - haveged
      - ntp
      - ntpdate
    state: latest

# Debian has bugs, sigh
- name: Configure OpenVPN (Debian)
  template:
    src: server_debian.conf
    dest: /etc/openvpn/gamoto.conf
  when: ansible_distribution == 'Debian'

- name: Configure OpenVPN (Ubuntu)
  template:
    src: server.conf
    dest: /etc/openvpn/gamoto.conf
  when: ansible_distribution == 'Ubuntu'

- name: Remove systemd sandbox
  replace:
    path: '/lib/systemd/system/openvpn@.service'
    regexp: '^(CapabilityBoundingSet.*)'
    replace: '#\1'

- name: Enable haveged service
  systemd:
    name: haveged
    enabled: yes
    state: started

- name: Enable OpenVPN service
  systemd:
    name: 'openvpn@gamoto'
    enabled: yes
