---
- name: Install packages
  package:
    name:
      - openvpn
      - haveged
    state: latest

- name: Configure OpenVPN
  template:
    src: server.conf
    dest: /etc/openvpn/gamoto.conf

- name: Remove stupid
  replace:
    path: '/lib/systemd/system/openvpn@.service'
    regexp: '^(CapabilityBoundingSet.*)'
    replace: '#\1'

- name: Enable haveged service
  systemd:
    name: haveged
    enabled: yes
    state: started

- name: Enable OpenVPN service
  systemd:
    name: 'openvpn@gamoto'
    enabled: yes
